trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'


- script: |
    echo "Node version:"
    node --version
    echo "NPM version:"
    npm --version
  displayName: 'Check Node and NPM versions'


- script: |
    echo "Project Directory Structure:"
    ls -R .
  displayName: 'List project files'


- script: |
    npm install
  displayName: 'Install dependencies'


- script: |
    echo "Installed node_modules:"
    ls node_modules
  displayName: 'List Installed Dependencies'


- script: |
    echo "Running TypeScript Compilation (No Emit)"
    npx tsc --noEmit --pretty --diagnostics
  displayName: 'Run TypeScript diagnostics'


- script: |
    npm run build
  displayName: 'Build the project'


- script: |
    echo "Checking build output in dist/ folder:"
    ls -R dist
  displayName: 'List build output directory'


- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: "60bd1c3bde3eb009f0cd3ea674a42b7b8438b623c219d8e2b5a485f9671cfd4606-d47ba54f-6a68-4c37-a282-e313c675cea701021300ba878c10"
    app_location: '/'
    output_location: 'dist'
    api_location: ''
  displayName: 'Deploy to Azure Static Web Apps'
