trigger:
  branches:
    include:
      - main  # Adjust this if your branch name is different

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the pipeline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the project'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)  # Store this in Azure DevOps as a secret
    app_location: '/'  # Change this if your app is inside a subfolder
    output_location: 'dist'  # Adjust this based on where your build output is
    api_location: ''  # Leave empty if you don't have an API backend
  displayName: 'Deploy to Azure Static Web Apps'
